// Code generated by sidecars/matter-server/tools/gen-matter-tables.mjs. DO NOT EDIT.
//
// Источник — модель данных CSA из matter.js. Правки руками будут стёрты:
// поменяй манифест в генераторе и перезапусти `npm run gen:tables`.

package matter

// genEnums — значения енумов в форме keystone, по ключу Cluster.EnumName.
var genEnums = map[string]map[int]string{
	"DoorLock.LockStateEnum": {
		0: "not_fully_locked",
		1: "locked",
		2: "unlocked",
		3: "unlatched",
	},
	"Thermostat.SystemModeEnum": {
		0: "off",
		1: "auto",
		3: "cool",
		4: "heat",
		5: "emergency_heat",
		6: "precooling",
		7: "fan_only",
		8: "dry",
		9: "sleep",
	},
	"FanControl.FanModeEnum": {
		0: "off",
		1: "low",
		2: "medium",
		3: "high",
		4: "on",
		5: "auto",
		6: "smart",
	},
	"AirQuality.AirQualityEnum": {
		0: "unknown",
		1: "good",
		2: "fair",
		3: "moderate",
		4: "poor",
		5: "very_poor",
		6: "extremely_poor",
	},
	"SmokeCoAlarm.AlarmStateEnum": {
		0: "normal",
		1: "warning",
		2: "critical",
	},
	"RvcOperationalState.OperationalStateEnum": {
		0:  "stopped",
		1:  "running",
		2:  "paused",
		3:  "error",
		64: "seeking_charger",
		65: "charging",
		66: "docked",
		67: "emptying_dust_bin",
		68: "cleaning_mop",
		69: "filling_water_tank",
		70: "updating_maps",
	},
	"MediaPlayback.PlaybackStateEnum": {
		0: "playing",
		1: "paused",
		2: "not_playing",
		3: "buffering",
	},
	"EnergyEvse.StateEnum": {
		0: "not_plugged_in",
		1: "plugged_in_no_demand",
		2: "plugged_in_demand",
		3: "plugged_in_charging",
		4: "plugged_in_discharging",
		5: "session_ending",
		6: "fault",
	},
	"EnergyEvse.SupplyStateEnum": {
		0: "disabled",
		1: "charging_enabled",
		2: "discharging_enabled",
		3: "disabled_error",
		4: "disabled_diagnostics",
		5: "enabled",
	},
	"ColorControl.ColorModeEnum": {
		0: "current_hue_and_current_saturation",
		1: "current_x_and_current_y",
		2: "color_temperature_mireds",
	},
	"ValveConfigurationAndControl.ValveStateEnum": {
		0: "closed",
		1: "open",
		2: "transitioning",
	},
}

// genAttribute описывает атрибут так, как его определяет спека.
type genAttribute struct {
	// Writable: спека разрешает запись. Если false — состояние меняется
	// только командой, а запись устройство молча проигнорирует.
	Writable bool
	// Gate: пусто — атрибут обязателен; иначе код фичи кластера (HS, XY,
	// CT) или "O" — присутствие зависит от устройства и должно
	// проверяться по его собственным спискам, а не предполагаться.
	Gate string
}

var genAttributes = map[string]genAttribute{
	"OnOff.OnOff":                                                 {Writable: false, Gate: ""},
	"LevelControl.CurrentLevel":                                   {Writable: false, Gate: ""},
	"ColorControl.CurrentHue":                                     {Writable: false, Gate: "HS"},
	"ColorControl.CurrentSaturation":                              {Writable: false, Gate: "HS"},
	"ColorControl.ColorTemperatureMireds":                         {Writable: false, Gate: "CT"},
	"ColorControl.ColorMode":                                      {Writable: false, Gate: ""},
	"DoorLock.LockState":                                          {Writable: false, Gate: ""},
	"WindowCovering.CurrentPositionLiftPercent100ths":             {Writable: false, Gate: "LF & PA_LF"},
	"Thermostat.LocalTemperature":                                 {Writable: false, Gate: ""},
	"Thermostat.OccupiedHeatingSetpoint":                          {Writable: true, Gate: "HEAT"},
	"Thermostat.OccupiedCoolingSetpoint":                          {Writable: true, Gate: "COOL"},
	"Thermostat.SystemMode":                                       {Writable: true, Gate: ""},
	"Thermostat.ThermostatRunningState":                           {Writable: false, Gate: "O"},
	"FanControl.FanMode":                                          {Writable: true, Gate: ""},
	"FanControl.PercentSetting":                                   {Writable: true, Gate: ""},
	"TemperatureControl.TemperatureSetpoint":                      {Writable: false, Gate: "TN"},
	"ValveConfigurationAndControl.CurrentState":                   {Writable: false, Gate: ""},
	"ValveConfigurationAndControl.CurrentLevel":                   {Writable: false, Gate: "LVL"},
	"RvcRunMode.CurrentMode":                                      {Writable: false, Gate: ""},
	"ModeSelect.CurrentMode":                                      {Writable: false, Gate: ""},
	"LaundryWasherMode.CurrentMode":                               {Writable: false, Gate: ""},
	"DishwasherMode.CurrentMode":                                  {Writable: false, Gate: ""},
	"RefrigeratorAndTemperatureControlledCabinetMode.CurrentMode": {Writable: false, Gate: ""},
	"WaterHeaterMode.CurrentMode":                                 {Writable: false, Gate: ""},
	"EnergyEvseMode.CurrentMode":                                  {Writable: false, Gate: ""},
	"MediaPlayback.CurrentState":                                  {Writable: false, Gate: ""},
	"EnergyEvse.State":                                            {Writable: false, Gate: ""},
	"EnergyEvse.SupplyState":                                      {Writable: false, Gate: ""},
}

// genRequiredArgs — обязательные аргументы команды (conformance M).
// Неполная команда не доходит до устройства: её отвергает валидация.
var genRequiredArgs = map[string][]string{
	"OnOff.On":                            {},
	"OnOff.Off":                           {},
	"OnOff.Toggle":                        {},
	"LevelControl.MoveToLevel":            {"level", "transitionTime", "optionsMask", "optionsOverride"},
	"LevelControl.MoveToLevelWithOnOff":   {"level", "transitionTime", "optionsMask", "optionsOverride"},
	"ColorControl.MoveToHue":              {"hue", "direction", "transitionTime", "optionsMask", "optionsOverride"},
	"ColorControl.MoveToSaturation":       {"saturation", "transitionTime", "optionsMask", "optionsOverride"},
	"ColorControl.MoveToHueAndSaturation": {"hue", "saturation", "transitionTime", "optionsMask", "optionsOverride"},
	"ColorControl.MoveToColor":            {"colorX", "colorY", "transitionTime", "optionsMask", "optionsOverride"},
	"ColorControl.MoveToColorTemperature": {"colorTemperatureMireds", "transitionTime", "optionsMask", "optionsOverride"},
	"DoorLock.LockDoor":                   {},
	"DoorLock.UnlockDoor":                 {},
	"WindowCovering.UpOrOpen":             {},
	"WindowCovering.DownOrClose":          {},
	"WindowCovering.StopMotion":           {},
	"WindowCovering.GoToLiftPercentage":   {"liftPercent100thsValue"},
	"MediaPlayback.Play":                  {},
	"MediaPlayback.Pause":                 {},
	"MediaPlayback.Stop":                  {},
	"MediaPlayback.Next":                  {},
	"MediaPlayback.Previous":              {},
	"SmokeCoAlarm.SelfTestRequest":        {},
	"EnergyEvse.EnableCharging":           {"chargingEnabledUntil", "minimumChargeCurrent", "maximumChargeCurrent"},
	"EnergyEvse.Disable":                  {},
	"ValveConfigurationAndControl.Open":   {},
	"ValveConfigurationAndControl.Close":  {},
	"TemperatureControl.SetTemperature":   {},
	"RvcRunMode.ChangeToMode":             {"newMode"},
	"ModeSelect.ChangeToMode":             {"newMode"},
	"LaundryWasherMode.ChangeToMode":      {"newMode"},
	"DishwasherMode.ChangeToMode":         {"newMode"},
	"RefrigeratorAndTemperatureControlledCabinetMode.ChangeToMode": {"newMode"},
	"WaterHeaterMode.ChangeToMode":                                 {"newMode"},
	"EnergyEvseMode.ChangeToMode":                                  {"newMode"},
	"Chime.PlayChimeSound":                                         {},
}
